### ISSUE TITLE
Selenium v3 can no longer be started, error " Was passed main parameter '-I' but no main parameter was defined in your arg class"

### ISSUE THREAD

**Issue by marcovtwout** [webdriverio/selenium-standalone#724]
## Expected Behavior
Selenium v3 should start normally.

## Current Behavior
```
$ selenium-standalone start --version=3.141.59
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '-I' but no main parameter was defined in your arg class
        at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:936)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:752)
        at com.beust.jcommander.JCommander.parse(JCommander.java:340)
        at com.beust.jcommander.JCommander.parse(JCommander.java:319)
        at org.openqa.grid.selenium.GridLauncherV3.parse(GridLauncherV3.java:218)
        at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$3(GridLauncherV3.java:241)
        at org.openqa.grid.selenium.GridLauncherV3.lambda$launch$0(GridLauncherV3.java:86)
        at java.base/java.util.Optional.map(Optional.java:265)
        at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:86)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:70)
/home/marco/test-selenium/node_modules/selenium-standalone/lib/check-started.js:44
      throw new Error(
            ^

Error: Selenium exited before it could start with code 1
Stdout:
Stderr:
    at checkStarted (/home/marco/test-selenium/node_modules/selenium-standalone/lib/check-started.js:44:13)
    at async Object.start (/home/marco/test-selenium/node_modules/selenium-standalone/lib/start.js:150:3)
    at async Object.start (/home/marco/test-selenium/node_modules/selenium-standalone/bin/selenium-standalone:23:16)
```

Running with `DEBUG=selenium-standalone:*` reveals the command that is executed:
```
 selenium-standalone:start Spawning Selenium Server process /usr/bin/java [
  '-Dwebdriver.chrome.driver=/home/marco/test-selenium/node_modules/selenium-standalone/.selenium/chromedriver/latest-x64/chromedriver',
  '-Dwebdriver.gecko.driver=/home/marco/test-selenium/node_modules/selenium-standalone/.selenium/geckodriver/latest-x64/geckodriver',
  '-Dwebdriver.edge.driver=/home/marco/test-selenium/node_modules/selenium-standalone/.selenium/chromiumedgedriver/latest-x64/msedgedriver',
  '-jar',
  '/home/marco/test-selenium/node_modules/selenium-standalone/.selenium/selenium-server/3.141.59/selenium-server.jar',
  '-I',
  'chrome',
  '-I',
  'firefox',
  '-I',
  'edge'
]
```

## Steps to Reproduce

```
selenium-standalone install --version=3.141.59
selenium-standalone start --version=3.141.59
```

## Analysis

This regression is introduced since: https://github.com/webdriverio/selenium-standalone/pull/670 
Selenium v3 does not seem to support the `-I` option which was added in this PR.

@eric1234 Perhaps the blocks of code like: https://github.com/webdriverio/selenium-standalone/blob/main/lib/start.js#L89-L93
```
args.push('-Dwebdriver.chrome.driver=' + fsPaths.chrome.installPath);
opts.seleniumArgs.push('-I');
opts.seleniumArgs.push('chrome');
```

Should have been written like this?

```
args.push('-Dwebdriver.chrome.driver=' + fsPaths.chrome.installPath);
if (isSelenium4(opts.version)) {
  opts.seleniumArgs.push('-I');
  opts.seleniumArgs.push('chrome');
}
```

**Comment by ArminazK** [comment]
Hi, confirming this. This PR broke selenium v3
Some findings:
- no passing '-I' argument, selenium v3 starts
- no passing '-I' argument, `programmatic.js` (start related) tests fail.

Solutions:
1.  (bad, but fast fix) just add those `if (isSelenium4(opts.version))...` as @marcovtwout suggested and tests will pass due to default selenium tests are for v4, so no test failure ()
2. (good, might take more time) fix tests and `lib/start.js' both for v3 and v4

Thanks

**Comment by udarrr** [comment]
Hi, I really wait for the merge and new version

But, I was wondering about what if we'd like to chage just opts.seleniumVersion with baseUrl like selenium-release.storage.googleapis.com
I think we could change also downloadUrls  in compute-download-urls.js
something like that 

const downloadUrls = {
  selenium: util.format(
    isSelenium4(opts.seleniumVersion) ? urls.seleniumV4 : urls.selenium,
    opts.seleniumBaseURL,
    isSelenium4(opts.seleniumVersion)
      ? `selenium-${getVersionWithZeroedPatchPart(opts.seleniumVersion)}`
      : opts.seleniumBaseURL.includes('selenium-release.storage.googleapis.com')
      ? opts.seleniumVersion.replace(/(\d+\.\d+)\.\d+/, '$1')
      : `selenium-${opts.seleniumVersion}`,
    opts.seleniumVersion,
  ),
};

**Comment by marcovtwout** [comment]
Confirmed that latest release fixes this issue, thanks!
