### ISSUE TITLE
Intermittent test failure

### ISSUE THREAD

**Issue by seanpoulter** [webdriverio/selenium-standalone#901]
There is at least one intermittent test failure in the CI pipeline:
https://github.com/webdriverio/selenium-standalone/actions/runs/8555104397/job/23441790222?pr=899

```
   133 passing (1m)
  1 failing

  1) check staring drivers twice with onlyDriver option
       check staring twice chromedriver:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test\only-driver-tests.js:96:5)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by udarrr** [comment]
it seems flaky, the same here https://github.com/webdriverio/selenium-standalone/actions/runs/9652863807/job/26623922473
possible because of timeout, i've increased timeout in  'port-is-reachable' method, let's see how it'll be working

one more test case especially for mac, for the rest os it's working as expected

  1 failing

  1) when files are installed
       should not reinstall them:

      AssertionError [ERR_ASSERTION]: It should not have reinstalled files
      + expected - actual

      -true
      +false
      
      at Context.<anonymous> (test/no-reinstall.js:41:12)
